import './globals.css';
import React from 'react';
import { CardProvider } from './cardProvider';

export const metadata = {
	title: 'Whatever Magic!',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<CardProvider>
			<html lang="en">
				<body>{children}</body>
			</html>
		</CardProvider>
	);
}
